### ISSUE TITLE
Heartrate acquisition assistance

### ISSUE THREAD

**Issue by VigneshK2000** [vatte/art-bio#3]
Hello,

My team and I are currently working on a project involving the art-bio repository you created, and we have a few questions.

We're able to connect to the Bitalino via your program and generate the .txt file but we are unable to understand how to convert it/output the HearRate Value.

As an alternative, we were trying to use the pyHRV module but we're running into the same issue mentioned here: https://github.com/vatte/art-bio/issues/2

Would you be able to describe to us exactly what values we are seeing in the data output (I have attached it) and/or how to convert to heart rate?
[temp.txt](https://github.com/vatte/art-bio/files/8346759/temp.txt)

Thank you so much for your help!

**Comment by vatte** [comment]
Hi, the inter-beat interval of the heart rate is given in seconds. To convert it into a bpm value to represent heart rate you would use the formula 60 / IBI, since there are 60 seconds in a minute. Your recording looks noisy though, as the IBI values are changing a lot between beats. Some variation is normal of course, but a heart rate calculation usually involves also some averaging over time and/or rejection of outlier values.
